ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = uno
\ ARDUINO_PORT = /dev/ttyACM*
ARD_PORT = /dev/ttyACM*
ARDUINO_LIBS = Serial
include /home/noah/Documents/arduino/Arduino.mk

AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF = /etc/avrdude.conf
